# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kelompok1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kelompok1(object):
    def setupUi(self, Kelompok1):
        Kelompok1.setObjectName("Kelompok1")
        Kelompok1.resize(341, 476)
        Kelompok1.setStyleSheet("background-color: rgb(15, 15, 15);")
        Kelompok1.setFixedSize(Kelompok1.size())
        self.centralwidget = QtWidgets.QWidget(Kelompok1)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.push_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_5.sizePolicy().hasHeightForWidth())
        self.push_5.setSizePolicy(sizePolicy)
        self.push_5.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_5.setObjectName("push_5")
        self.gridLayout.addWidget(self.push_5, 3, 1, 1, 1)
        self.push_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_3.sizePolicy().hasHeightForWidth())
        self.push_3.setSizePolicy(sizePolicy)
        self.push_3.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_3.setObjectName("push_3")
        self.gridLayout.addWidget(self.push_3, 2, 2, 1, 1)
        self.push_equal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_equal.sizePolicy().hasHeightForWidth())
        self.push_equal.setSizePolicy(sizePolicy)
        self.push_equal.setStyleSheet("QPushButton{\n"
"font: 75 36pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 127);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}")
        self.push_equal.setObjectName("push_equal")
        self.gridLayout.addWidget(self.push_equal, 5, 3, 1, 1)
        self.push_min = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_min.sizePolicy().hasHeightForWidth())
        self.push_min.setSizePolicy(sizePolicy)
        self.push_min.setStyleSheet("QPushButton{\n"
"font: 75 36pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 127);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}")
        self.push_min.setObjectName("push_min")
        self.gridLayout.addWidget(self.push_min, 2, 3, 1, 1)
        self.push_del = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_del.sizePolicy().hasHeightForWidth())
        self.push_del.setSizePolicy(sizePolicy)
        self.push_del.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(185, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(185, 0, 0);\n"
"}\n"
"")
        self.push_del.setObjectName("push_del")
        self.gridLayout.addWidget(self.push_del, 1, 2, 1, 1)
        self.push_point = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_point.sizePolicy().hasHeightForWidth())
        self.push_point.setSizePolicy(sizePolicy)
        self.push_point.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_point.setObjectName("push_point")
        self.gridLayout.addWidget(self.push_point, 5, 2, 1, 1)
        self.push_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_1.sizePolicy().hasHeightForWidth())
        self.push_1.setSizePolicy(sizePolicy)
        self.push_1.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_1.setObjectName("push_1")
        self.gridLayout.addWidget(self.push_1, 2, 0, 1, 1)
        self.push_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_2.sizePolicy().hasHeightForWidth())
        self.push_2.setSizePolicy(sizePolicy)
        self.push_2.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_2.setObjectName("push_2")
        self.gridLayout.addWidget(self.push_2, 2, 1, 1, 1)
        self.push_mult = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_mult.sizePolicy().hasHeightForWidth())
        self.push_mult.setSizePolicy(sizePolicy)
        self.push_mult.setStyleSheet("QPushButton{\n"
"font: 75 36pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 127);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}")
        self.push_mult.setObjectName("push_mult")
        self.gridLayout.addWidget(self.push_mult, 3, 3, 1, 1)
        self.push_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_9.sizePolicy().hasHeightForWidth())
        self.push_9.setSizePolicy(sizePolicy)
        self.push_9.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_9.setObjectName("push_9")
        self.gridLayout.addWidget(self.push_9, 4, 2, 1, 1)
        self.push_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_8.sizePolicy().hasHeightForWidth())
        self.push_8.setSizePolicy(sizePolicy)
        self.push_8.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_8.setObjectName("push_8")
        self.gridLayout.addWidget(self.push_8, 4, 1, 1, 1)
        self.push_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_4.sizePolicy().hasHeightForWidth())
        self.push_4.setSizePolicy(sizePolicy)
        self.push_4.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_4.setObjectName("push_4")
        self.gridLayout.addWidget(self.push_4, 3, 0, 1, 1)
        self.push_zero = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_zero.sizePolicy().hasHeightForWidth())
        self.push_zero.setSizePolicy(sizePolicy)
        self.push_zero.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_zero.setObjectName("push_zero")
        self.gridLayout.addWidget(self.push_zero, 5, 0, 1, 2)
        self.push_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_6.sizePolicy().hasHeightForWidth())
        self.push_6.setSizePolicy(sizePolicy)
        self.push_6.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_6.setObjectName("push_6")
        self.gridLayout.addWidget(self.push_6, 3, 2, 1, 1)
        self.push_div = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_div.sizePolicy().hasHeightForWidth())
        self.push_div.setSizePolicy(sizePolicy)
        self.push_div.setStyleSheet("QPushButton{\n"
"font: 75 36pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 127);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}")
        self.push_div.setObjectName("push_div")
        self.gridLayout.addWidget(self.push_div, 4, 3, 1, 1)
        self.push_plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_plus.sizePolicy().hasHeightForWidth())
        self.push_plus.setSizePolicy(sizePolicy)
        self.push_plus.setStyleSheet("QPushButton{\n"
"font: 75 36pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 127);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(230, 230, 0);\n"
"}")
        self.push_plus.setObjectName("push_plus")
        self.gridLayout.addWidget(self.push_plus, 1, 3, 1, 1)
        self.push_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_7.sizePolicy().hasHeightForWidth())
        self.push_7.setSizePolicy(sizePolicy)
        self.push_7.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(52, 157, 77);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(52, 157, 77);\n"
"}")
        self.push_7.setObjectName("push_7")
        self.gridLayout.addWidget(self.push_7, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 75 36pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.push_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_clear.sizePolicy().hasHeightForWidth())
        self.push_clear.setSizePolicy(sizePolicy)
        self.push_clear.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(185, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(185, 0, 0);\n"
"}")
        self.push_clear.setObjectName("push_clear")
        self.gridLayout.addWidget(self.push_clear, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        Kelompok1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Kelompok1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 341, 21))
        self.menubar.setObjectName("menubar")
        Kelompok1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Kelompok1)
        self.statusbar.setObjectName("statusbar")
        Kelompok1.setStatusBar(self.statusbar)

        self.retranslateUi(Kelompok1)
        QtCore.QMetaObject.connectSlotsByName(Kelompok1)


        self.push_1.clicked.connect(self.method_1)
        self.push_2.clicked.connect(self.method_2)
        self.push_3.clicked.connect(self.method_3)
        self.push_4.clicked.connect(self.method_4)
        self.push_5.clicked.connect(self.method_5)
        self.push_6.clicked.connect(self.method_6)
        self.push_7.clicked.connect(self.method_7)
        self.push_8.clicked.connect(self.method_8)
        self.push_9.clicked.connect(self.method_9)
        self.push_zero.clicked.connect(self.method_zero)
        self.push_point.clicked.connect(self.method_point)
        self.push_plus.clicked.connect(self.method_plus)
        self.push_min.clicked.connect(self.method_min)
        self.push_mult.clicked.connect(self.method_mult)
        self.push_div.clicked.connect(self.method_div)
        self.push_equal.clicked.connect(self.method_equal)
        self.push_clear.clicked.connect(self.method_clear)
        self.push_del.clicked.connect(self.method_del)

    def method_1(self):
        text=self.label.text()
        self.label.setText(text+"1")

    def method_2(self):
        text=self.label.text()
        self.label.setText(text+"2")

    def method_3(self):
        text=self.label.text()
        self.label.setText(text+"3")

    def method_4(self):
        text=self.label.text()
        self.label.setText(text+"4")

    def method_5(self):
        text=self.label.text()
        self.label.setText(text+"5")

    def method_6(self):
        text=self.label.text()
        self.label.setText(text+"6")

    def method_7(self):
        text=self.label.text()
        self.label.setText(text+"7")       

    def method_8(self):
        text=self.label.text()
        self.label.setText(text+"8")

    def method_9(self):
        text=self.label.text()
        self.label.setText(text+"9")
        
    def method_zero(self):
        text=self.label.text()
        self.label.setText(text+"0")

    def method_point(self):
        text=self.label.text()
        self.label.setText(text+".")

    def method_plus(self):
        text=self.label.text()
        self.label.setText(text+"+")

    def method_min(self):
        text=self.label.text()
        self.label.setText(text+"-")

    def method_mult(self):
        text=self.label.text()
        self.label.setText(text+"*")

    def method_div(self):
        text=self.label.text()
        self.label.setText(text+"/")

    def method_clear(self):
        self.label.setText("")

    def method_del(self):
        text=self.label.text()
        self.label.setText(text[:len(text)-1])

    def method_equal(self):
        text=self.label.text()

        try:
            ans=eval(text)
            self.label.setText(str(ans))
        except:
            self.label.setText("Wrong Input")        

    def retranslateUi(self, Kelompok1):
        _translate = QtCore.QCoreApplication.translate
        Kelompok1.setWindowTitle(_translate("Kelompok1", "Kalkulator Kelompok 1"))
        self.push_5.setText(_translate("Kelompok1", "5"))
        self.push_5.setShortcut(_translate("Kelompok1", "5"))
        self.push_3.setText(_translate("Kelompok1", "3"))
        self.push_3.setShortcut(_translate("Kelompok1", "3"))
        self.push_equal.setText(_translate("Kelompok1", "="))
        self.push_equal.setShortcut(_translate("Kelompok1", "="))
        self.push_min.setText(_translate("Kelompok1", "-"))
        self.push_min.setShortcut(_translate("Kelompok1", "-"))
        self.push_del.setText(_translate("Kelompok1", "Del"))
        self.push_del.setShortcut(_translate("Kelompok1", "Del"))
        self.push_point.setText(_translate("Kelompok1", "."))
        self.push_point.setShortcut(_translate("Kelompok1", "."))
        self.push_1.setText(_translate("Kelompok1", "1"))
        self.push_1.setShortcut(_translate("Kelompok1", "1"))
        self.push_2.setText(_translate("Kelompok1", "2"))
        self.push_2.setShortcut(_translate("Kelompok1", "2"))
        self.push_mult.setText(_translate("Kelompok1", "x"))
        self.push_mult.setShortcut(_translate("Kelompok1", "*"))
        self.push_9.setText(_translate("Kelompok1", "9"))
        self.push_9.setShortcut(_translate("Kelompok1", "9"))
        self.push_8.setText(_translate("Kelompok1", "8"))
        self.push_8.setShortcut(_translate("Kelompok1", "8"))
        self.push_4.setText(_translate("Kelompok1", "4"))
        self.push_4.setShortcut(_translate("Kelompok1", "4"))
        self.push_zero.setText(_translate("Kelompok1", "0"))
        self.push_zero.setShortcut(_translate("Kelompok1", "0"))
        self.push_6.setText(_translate("Kelompok1", "6"))
        self.push_6.setShortcut(_translate("Kelompok1", "6"))
        self.push_div.setText(_translate("Kelompok1", "÷"))
        self.push_div.setShortcut(_translate("Kelompok1", "/"))
        self.push_plus.setText(_translate("Kelompok1", "+"))
        self.push_plus.setShortcut(_translate("Kelompok1", "+"))
        self.push_7.setText(_translate("Kelompok1", "7"))
        self.push_7.setShortcut(_translate("Kelompok1", "7"))
        self.push_clear.setText(_translate("Kelompok1", "Clear"))
        self.push_clear.setShortcut(_translate("Kelompok1", "Backspace"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kelompok1 = QtWidgets.QMainWindow()
    ui = Ui_Kelompok1()
    ui.setupUi(Kelompok1)
    Kelompok1.show()
    sys.exit(app.exec_())
